output "generated_project_id" {
  description = "The Google Cloud project ID generated by Terraform."
  value       = module.project.project_id
}

output "deploy_service_account_email" {
  description = "The email of the service account used for deployments."
  value       = module.service_account.email
}